services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./infra/db:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -P $$POSTGRES_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5

  db-test:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - 5433:5432
    volumes:
      - ./infra/db:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -P $$POSTGRES_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5
